# --- DarkForge-X: CI/CD "Living Weapon" Payload v2.2 ---
# Финальная калибровка: Устранена синтаксическая неоднозначность YAML.

name: Network Reconnaissance Strike

on:
  workflow_dispatch:
    inputs:
      target_range:
        description: 'Target CIDR (e.g., 8.8.8.0/24)'
        required: true
        default: 'scanme.nmap.org'
      ports:
        description: 'Ports to scan (e.g., 21,22,80,443)'
        required: true
        default: '22,80,443'
      rate:
        description: 'Masscan rate (packets/sec)'
        required: true
        default: '10000'

jobs:
  execute-scan:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Arming the Runner (Install Masscan)
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan

      - name: 2. Launching Strike (Execute Masscan)
        run: |
          echo "Scanning target ${{ github.event.inputs.target_range }} on ports ${{ github.event.inputs.ports }} with rate ${{ github.event.inputs.rate }}"
          # ИСПРАВЛЕНИЕ: Целевой диапазон заключен в кавычки для корректной обработки парсером YAML.
          sudo masscan -p${{ github.event.inputs.ports }} --rate ${{ github.event.inputs.rate }} --open-only --banners -oJ scan_results.json "${{ github.event.inputs.target_range }}"

      - name: 3. Exfiltrating Intelligence (Upload Artifact v4)
        uses: actions/upload-artifact@v4
        with:
          name: recon-results
          path: scan_results.json
