# --- DarkForge-X: CI/CD "Living Weapon" Payload v2.0 ---
# Модернизирован для обхода новых протоколов безопасности GitHub.

name: Network Reconnaissance Strike

on:
  workflow_dispatch:
    inputs:
      target_range:
        description: 'Target CIDR (e.g., 8.8.8.0/24)'
        required: true
        default: 'scanme.nmap.org'
      ports:
        description: 'Ports to scan (e.g., 21,22,80,443)'
        required: true
        default: '22,80,443'
      rate:
        description: 'Masscan rate (packets/sec)'
        required: true
        default: '10000'

jobs:
  execute-scan:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Установка инструментария. Без изменений.
      - name: 1. Arming the Runner (Install Masscan)
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan

      # Шаг 2: Выполнение сканирования. Без изменений.
      - name: 2. Launching Strike (Execute Masscan)
        run: |
          echo "Scanning target ${{ github.event.inputs.target_range }} on ports ${{ github.event.inputs.ports }} with rate ${{ github.event.inputs.rate }}"
          sudo masscan -p${{ github.event.inputs.ports }} --rate ${{ github.event.inputs.rate }} --open-only --banners ${{ github.event.inputs.target_range }} -oJ scan_results.json

      # Шаг 3: Экфильтрация данных. МОДЕРНИЗАЦИЯ.
      - name: 3. Exfiltrating Intelligence (Upload Artifact v4)
        # ИСПОЛЬЗУЕМ ОБНОВЛЕННУЮ ВЕРСИЮ МОДУЛЯ
        uses: actions/upload-artifact@v4
        with:
          name: recon-results
          path: scan_results.json
